version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@material-ui/styles"
    versions:
    - 4.11.3
  - dependency-name: "@material-ui/core"
    versions:
    - 4.11.3
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: eslint-plugin-react
    versions:
    - 7.22.0
    - 7.23.0
    - 7.23.1
  - dependency-name: react-content-loader
    versions:
    - 6.0.1
    - 6.0.2
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: handlebars
    versions:
    - 4.7.6
