language: node_js
node_js:
- '8.4.0'
notifications:
  email:
  - howardc93@gmail.com
  - aqc2109@columbia.edu
  - mjr127@case.edu
script:
- npm run build
# blocklist
branches:
  except:
  - l10n_master
